#!/bin/bash

# See also: https://blogs.gentoo.org/ago/2019/03/20/install-gentoo-in-less-than-one-minute/

clear

GITHUB="https://github.com/asarubbo/gentoo-stage4/raw/master"

####### USER CONFIGS
#STAGE4_URL="https://dev.gentoo.org/~ago/stage4/stage4-hardened-20221017.tar.xz" ; MD5SUM="ed456edca0996a53b58915be89848619"
#STAGE4_URL="https://dev.gentoo.org/~ago/stage4/stage4-standard-20221017.tar.xz" ; MD5SUM="6d6b2a161d32c25295ee905778427dab"

DISK="/dev/sda"
ESP="/dev/sda1"
BOOT="/dev/sda2"
ROOT="/dev/sda3"
ROOTFS_MKFS_COMMAND=" -t btrfs -f "  #use BTRFS, force formatting
ROOT_PASSWORD=`cat /dev/urandom | tr -dc a-zA-Z0-9 | fold -w 14 | head -n 1`
LOG_FILE="/dev/null"
#LOG_FILE="log.txt" # to enable logging to file
##########

echo "Detailed output will be sent to ${LOG_FILE}"
LOCALTIME_URL="${GITHUB}/misc/CET"
PARTED_URL="${GITHUB}/misc/parted.txt"
MOUNTPOINT="/mnt/gentoo"
INITIAL_PWD="$( pwd )"

echo -ne "\nBefore to run this script you need to configure the basics in the script itself\n\n"
echo "This script will COMPLETELY erase your disk $DISK (see line 58)"
read -r -p "Are you sure? [y/N] " RESPONSE
RESPONSE=${RESPONSE,,}
if [[ ! "$RESPONSE" =~ ^(yes|y)$ ]]
then
        echo "Aborting..."
        exit 1
fi

if [ -z "${STAGE4_URL}" ]
then
        echo "You need to delete the comment from one of the available STAGE4_URL and its MD5SUM and relaunch the script"
        exit 1
fi

function die () {
        if [ "${?}" != "0" ]
        then
                echo "Something went wrong; aborting... $1"
                exit 1
        fi
}

# DATE/NTP
rm -fr /etc/localtime
curl -s -q -L "${LOCALTIME_URL}" --output /etc/localtime
ntpdate -b time.ien.it > ${LOG_FILE} 2>&1 && hwclock -w

echo "CLEAN THE DISK"
dd if=/dev/zero of="${DISK}" bs=512 count=1 conv=notrunc >> ${LOG_FILE} 2>&1 || die "Can not clean disk"

cd /tmp/
curl -s -q -L "${PARTED_URL}" --output parted.txt || die
sed "s:CHANGEME:${DISK}:" -i parted.txt || die
parted -a optimal < ./parted.txt >> ${LOG_FILE} 2>&1 || die
echo "MAKE FILESYSTEMS"
echo "mkfs.ext4 -F ${BOOT} >> ${LOG_FILE} 2>&1"
mkfs.ext4 -F "${BOOT}" >> ${LOG_FILE} 2>&1 || die "mkfs for ${BOOT}"
echo "mkfs ${ROOTFS_MKFS_COMMAND}  ${ROOT} >> ${LOG_FILE} 2>&1"
mkfs ${ROOTFS_MKFS_COMMAND}   "${ROOT}" >> ${LOG_FILE} 2>&1 || die "mkfs for ${ROOT}"
mkdir -p "${MOUNTPOINT}" || die
mount "${ROOT}" "${MOUNTPOINT}" || die "mount for ${ROOT}"
mkdir -p "${MOUNTPOINT}"/boot || die
mount "${BOOT}" "${MOUNTPOINT}"/boot || die "mount for ${BOOT}"
cd "${MOUNTPOINT}" || die
echo "DOWNLOAD IN PROGRESS..."
curl  -q -L "${STAGE4_URL}" --output stage4.tar.xz || die
echo "DOWNLOAD DONE..."
echo "MD5SUM CHECK IN PROGRESS..."
if [ "$( md5sum stage4.tar.xz | awk '{print $1}' )" != "${MD5SUM}" ]
then
        echo "Something wrong with the MD5SUM"
        exit 1
fi
echo "MD5SUM CHECK DONE..."
echo "DECOMPRESSION IN PROGRESS..."
tar -xJpf stage4.tar.xz || die
echo "DECOMPRESSION DONE..."
rm -fr stage4.tar.xz || die


####
sed "s:j4:j$( nproc ):" -i etc/portage/make.conf
sed "s:BOOT:$BOOT:" -i etc/fstab || die
sed "s:ROOT:$ROOT:" -i etc/fstab etc/default/grub || die
sed '/EFI/d' -i etc/fstab || die
####

#### NETWORK ####
IP_ADDRESS="$( ifconfig eth0 | grep "inet " | awk '{print $2}' )"
NETMASK="$( ifconfig eth0 | grep "inet " | awk '{print $4}' )"
BROADCAST="$( ifconfig eth0 | grep "inet " | awk '{print $6}' )"

cat >> etc/conf.d/net <<EOF
config_eth0="${IP_ADDRESS} netmask ${NETMASK} brd ${BROADCAST}"
routes_eth0="172.31.1.1 scope link
169.254.0.0/16 scope link metric 1002
default via 172.31.1.1"
EOF

mkdir dev proc run sys tmp >> ${LOG_FILE} 2>&1
mount -t proc proc "${MOUNTPOINT}"/proc || die
mount --rbind /sys "${MOUNTPOINT}"/sys || die
mount --rbind /dev "${MOUNTPOINT}"/dev || die

# KERNEL
rm -fr "${MOUNTPOINT}"/boot/*gentoo-sources-image* "${MOUNTPOINT}"/lib/modules/*

# CHROOT COMMANDS

export DISK="${DISK}"

echo -ne "\n\nGRUB:\n"
chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" grub-install $DISK' || die
chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" grub-mkconfig -o /boot/grub/grub.cfg' || die
chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" rc-update add net.eth0 default' >> ${LOG_FILE} 2>&1 || die
echo "root:{$ROOT_PASSWORD}" | chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" chpasswd' >> ${LOG_FILE} || die

rm -fr root/.ssh/authorized_keys || die

if [ -f "${INITIAL_PWD}"/id_rsa.pub ]
then
        echo "Copying public key from id_rsa.pub to target"
        cp "${INITIAL_PWD}"/id_rsa.pub root/.ssh/authorized_keys || die
else
        if [ -f "${INITIAL_PWD}"/.ssh/authorized_keys ]
        then
            echo "Copying authorized keys to target"
            cp "${INITIAL_PWD}"/.ssh/authorized_keys root/.ssh/authorized_keys || die
        else
            echo "No ssh keys found, you will have to set it up manually"
        fi        
fi


echo -ne "LSPCI -k:\n$( lspci -k | grep "Kernel\ driver" | sort | uniq )\n\nLSMOD:\n$( lsmod )\n" > "${MOUNTPOINT}"/root/.modules_info

echo "Your root password was set to ${ROOT_PASSWORD} "
echo -ne "\n\n\nTHE STAGE4 INSTALLATION HAS BEEN COMPLETED....HAVE A NICE DAY ;)\n"
