#!/bin/bash

# See also: https://blogs.gentoo.org/ago/2019/03/20/install-gentoo-in-less-than-one-minute/

clear

GITHUB="https://github.com/asarubbo/gentoo-stage4/raw/master"

####### USER CONFIGS
#TYPE="uefi"
#TYPE="bios"

#STAGE4_URL="https://dev.gentoo.org/~ago/stage4/stage4-hardened-20230206.tar.xz" ; MD5SUM="ed456edca0996a53b58915be89848619"
#STAGE4_URL="https://dev.gentoo.org/~ago/stage4/stage4-standard-20230206.tar.xz" ; MD5SUM="6d6b2a161d32c25295ee905778427dab"

DISK="/dev/sda"
ESP="/dev/sda1"
BOOT="/dev/sda2"
ROOT="/dev/sda3"
##########

LOCALTIME_URL="${GITHUB}/misc/CET"
PARTED_URL="${GITHUB}/misc/parted.txt"
MOUNTPOINT="/mnt/gentoo"
INITIAL_PWD="$( pwd )"

echo -ne "\nBefore to run this script you need to configure the basics in the script itself\n\n"
echo "This script will COMPLETELY erase your disk $DISK (see line 67)"
read -r -p "Are you sure? [y/N] " RESPONSE
RESPONSE=${RESPONSE,,}
if [[ ! "$RESPONSE" =~ ^(yes|y)$ ]]
then
	echo "Aborting..."
	exit 1
fi

if [ -z "${TYPE}" ]
then
	echo "You need to delete the comment from one of the available TYPES and relaunch the script"
	exit 1
fi

if [ -z "${STAGE4_URL}" ]
then
	echo "You need to delete the comment from one of the available STAGE4_URL and its MD5SUM and relaunch the script"
	exit 1
fi

function die () {
	if [ "${?}" != "0" ]
	then
		echo "Something went wrong; aborting..."
		exit 1
	fi
}

# DATE/NTP
rm -fr /etc/localtime
curl -s -q -L "${LOCALTIME_URL}" --output /etc/localtime
ntpdate -b time.ien.it > /dev/null 2>&1 && hwclock -w

# CLEAN THE DISK
dd if=/dev/zero of="${DISK}" bs=512 count=1 conv=notrunc > /dev/null 2>&1 || die

cd /tmp/
curl -s -q -L "${PARTED_URL}" --output parted.txt || die
sed "s:CHANGEME:${DISK}:" -i parted.txt || die
parted -a optimal < ./parted.txt > /dev/null 2>&1 || die
mkfs.ext4 -F "${BOOT}" > /dev/null 2>&1 || die
mkfs.ext4 -F "${ROOT}" > /dev/null 2>&1 || die
mkdir -p "${MOUNTPOINT}" || die
mount "${ROOT}" "${MOUNTPOINT}" || die
mkdir -p "${MOUNTPOINT}"/boot || die
mount "${BOOT}" "${MOUNTPOINT}"/boot || die
cd "${MOUNTPOINT}" || die
echo "DOWNLOAD IN PROGRESS..."
curl -s -q -L "${STAGE4_URL}" --output stage4.tar.xz || die
echo "DOWNLOAD DONE..."
echo "MD5SUM CHECK IN PROGRESS..."
if [ "$( md5sum stage4.tar.xz | awk '{print $1}' )" != "${MD5SUM}" ]
then
	echo "Something wrong with the MD5SUM"
	exit 1
fi
echo "MD5SUM CHECK DONE..."
echo "DECOMPRESSION IN PROGRESS..."
tar -xJpf stage4.tar.xz || die
echo "DECOMPRESSION DONE..."
rm -fr stage4.tar.xz || die


####
sed "s:j4:j$( nproc ):" -i etc/portage/make.conf
sed "s:BOOT:$BOOT:" -i etc/fstab || die
sed "s:ROOT:$ROOT:" -i etc/fstab etc/default/grub || die
####

mkdir dev proc run sys tmp > /dev/null 2>&1
mount -t proc proc "${MOUNTPOINT}"/proc || die
mount --rbind /sys "${MOUNTPOINT}"/sys || die
mount --rbind /dev "${MOUNTPOINT}"/dev || die

# KERNEL
rm -fr "${MOUNTPOINT}"/boot/*hetzner*


# CHROOT COMMANDS

export DISK="${DISK}"

echo -ne "\n\nGRUB:\n"
if [ "${TYPE}" = "uefi" ]
then
	mkfs.fat -F32 "${ESP}" || die
	mkdir -p "${MOUNTPOINT}"/boot/efi
	mount -t vfat "${ESP}" "${MOUNTPOINT}"/boot/efi || die
	chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" grub-install --target=x86_64-efi --efi-directory=/boot/efi $DISK' || die
elif [ "${TYPE}" = "bios" ]
then
	sed '/EFI/d' -i etc/fstab || die
	chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" grub-install $DISK' || die
fi

chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" grub-mkconfig -o /boot/grub/grub.cfg' || die
chroot "${MOUNTPOINT}" /bin/bash -c 'PATH="/usr/sbin:/usr/bin:/sbin:/bin" echo "root:ChangeMe1999" | chpasswd' || die

rm -fr root/.ssh/authorized_keys || die

if [ -f "${INITIAL_PWD}"/id_rsa.pub ]
then
	cp "${INITIAL_PWD}"/id_rsa.pub root/.ssh/authorized_keys || die
fi

echo -ne "LSPCI -k:\n$( lspci -k | grep "Kernel\ driver" | sort | uniq )\n\nLSMOD:\n$( lsmod )\n" > "${MOUNTPOINT}"/root/.modules_info

echo -ne "\n\n\nTHE STAGE4 INSTALLATION HAS BEEN COMPLETED....HAVE A NICE DAY ;)\n"
